--회원 정보 수정
UPDATE MEMBER
SET MEMBER_NAME  = ?,
    MEMBER_PASS  = ?,
    MEMBER_PHONE = ?,
    MEMBER_EMAIL = ?
WHERE MEMBER_NO = ?
;
--책 정보 수정
UPDATE BOOK
SET BOOK_TITLE     = ?,
    BOOK_CATEGORY  = ?,
    BOOK_AUTHOR    = ?,
    BOOK_PUBLISHER = ?,
    BOOK_YOP       = ?,
    BOOK_INFO      = ?,
    BOOK_INDEX     = ?,
    BOOK_IMAGE_URL = ?
WHERE BOOK_NO = ?
;
--책 반납(대출에서 접근권한을 없애고 회원과 책에서 대출 제한 - 1)
UPDATE LOAN SET LOAN_ACCESS = 0, LOAN_RETURN_DATE = SYSDATE
WHERE MEMBER_NO = ? AND BOOK_NO = ?
;
UPDATE MEMBER SET MEMBER_LOAN = MEMBER_LOAN - 1 WHERE MEMBER_NO = ?
;
UPDATE BOOK SET BOOK_LOAN = BOOK_LOAN - 1 WHERE BOOK_NO = ?
;
--공지사항 수정
UPDATE NOTICE
SET NOTICE_TITLE   = ?,
    NOTICE_CONTENT = ?,
    NOTICE_FILE    = ?
WHERE NOTICE_NO = ?
;
--QNA 조회수 증가
UPDATE QNA SET QNA_VIEWS = QNA_VIEWS + 1 WHERE QNA_NO = ?
;
--QNA 수정
UPDATE QNA
SET qna_title   = ?,
    qna_content = ?
WHERE QNA_NO = ?
  AND MEMBER_NO = ?
;
--QNA 답변 수정
UPDATE REPLY SET REPLY_CONTENT = ? WHERE REPLY_NO = ?
;
--FAQ 내용 수정
UPDATE FAQ SET FAQ_ANSWER = ? WHERE FAQ_NO = ?
;
--대출 추가
UPDATE BOOK SET BOOK_LOAN = BOOK_LOAN + 1 WHERE BOOK_NO = ?
;
UPDATE MEMBER SET MEMBER_LOAN = MEMBER_LOAN + 1 WHERE MEMBER_NO = ?
;
--예약 추가
UPDATE MEMBER SET MEMBER_RESERVATION = MEMBER_RESERVATION + 1 WHERE MEMBER_NO = ?
;
UPDATE BOOK SET BOOK_RESERVATION = BOOK_RESERVATION + 1 WHERE BOOK_NO = ?
;

