--회원 한명 정보
SELECT * FROM MEMBER WHERE MEMBER_NO = ?
;
/*
회원 서비스 이용 현황
 */
-- 회원 1명 대출 수
SELECT COUNT(*) CNT FROM LOAN WHERE MEMBER_NO = ? AND LOAN_ACCESS = 1
;
-- 회원 1명 반납 수 (최근 3개월??)
SELECT COUNT(*) CNT FROM LOAN WHERE MEMBER_NO = ? AND LOAN_ACCESS = 0
;
-- 회원 1명 관심도서 수
SELECT COUNT(*) CNT FROM FAVORITE WHERE MEMBER_NO = ?
;
-- 회원 1명 희망도서 수
SELECT COUNT(*) CNT FROM HOPE_BOOK WHERE MEMBER_NO = ?
;
--한 멤버의 대출현황
SELECT L.BOOK_NO, B.BOOK_CATEGORY, B.BOOK_TITLE, B.BOOK_AUTHOR,
       B.BOOK_PUBLISHER, B.BOOK_IMAGE_URL, B.BOOK_YOP,
       L.LOAN_REG_DATE, L.LOAN_RETURN_DATE
FROM LOAN   L
JOIN MEMBER M
     ON L.MEMBER_NO = M.MEMBER_NO
JOIN BOOK   B
     ON L.BOOK_NO = B.BOOK_NO
WHERE L.MEMBER_NO = ?
  AND L.LOAN_ACCESS = 1
;
--한 멤버의 예약현황
SELECT R.BOOK_NO, RESERVATION_REG_DATE, B.BOOK_TITLE,
       B.BOOK_AUTHOR, B.BOOK_PUBLISHER, B.BOOK_CATEGORY,
       B.BOOK_INFO, B.BOOK_INDEX, B.BOOK_IMAGE_URL
FROM RESERVATION R
JOIN BOOK        B
     ON B.BOOK_NO = R.BOOK_NO
WHERE MEMBER_NO = ?
;
--한 멤버의 반납현황
SELECT L.BOOK_NO, LOAN_RETURN_DATE, B.BOOK_TITLE,
       B.BOOK_AUTHOR, B.BOOK_PUBLISHER, B.BOOK_CATEGORY,
       B.BOOK_IMAGE_URL
FROM LOAN L
JOIN BOOK B
     ON B.BOOK_NO = L.BOOK_NO
WHERE MEMBER_NO = ?
  AND LOAN_ACCESS = 0
;
--한 멤버의 관심도서 목록
SELECT B.BOOK_NO, BOOK_TITLE, BOOK_AUTHOR,
       BOOK_CATEGORY, BOOK_HOLDINGS, BOOK_LOAN,
       BOOK_RESERVATION, BOOK_IMAGE_URL
FROM FAVORITE F
JOIN BOOK     B
     ON F.BOOK_NO = B.BOOK_NO
WHERE F.MEMBER_NO = ?
;
--한 멤버의 희망도서 목록
SELECT * FROM HOPE_BOOK WHERE MEMBER_NO = ?
;
--책 한권 정보
SELECT BOOK_NO, BOOK_TITLE, BOOK_AUTHOR,
       BOOK_INFO, BOOK_CATEGORY, BOOK_IMAGE_URL,
       BOOK_INDEX, BOOK_PUBLISHER, BOOK_HOLDINGS,
       BOOK_LOAN, BOOK_RESERVATION, BOOK_YOP
FROM BOOK
WHERE BOOK_NO = ?
;
--제목으로 책 검색(부분 문자로 찾기)
SELECT BOOK_NO, BOOK_TITLE, BOOK_AUTHOR,
       BOOK_YOP, BOOK_INFO, BOOK_CATEGORY,
       BOOK_IMAGE_URL, BOOK_INDEX, BOOK_PUBLISHER,
       BOOK_HOLDINGS, BOOK_LOAN, BOOK_RESERVATION
FROM BOOK
WHERE BOOK_TITLE LIKE '%' || ? || '%'
;
--카테고리로 책 검색
SELECT BOOK_NO, BOOK_TITLE, BOOK_AUTHOR,
       BOOK_INFO, BOOK_CATEGORY, BOOK_IMAGE_URL,
       BOOK_INDEX, BOOK_PUBLISHER, BOOK_HOLDINGS,
       BOOK_LOAN, BOOK_RESERVATION
FROM BOOK
WHERE BOOK_CATEGORY = ?
  AND BOOK_TITLE LIKE '%' || ? || '%'
;
--FAQ 목록 보기
SELECT FAQ_NO, FAQ_QUESTION, FAQ_ANSWER, FAQ_CATEGORY FROM FAQ
;
--공지사항 목록보기
SELECT NOTICE_NO, NOTICE_TITLE, NOTICE_REG_DATE, NOTICE_VIEWS FROM NOTICE
;
--공지사항 하나 상세보기
SELECT NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT,
       NOTICE_REG_DATE, NOTICE_FILE, NOTICE_VIEWS
FROM NOTICE
WHERE NOTICE_NO = ?
;
--QNA 목록 보기
SELECT QNA_NO, QNA_TITLE, QNA_REG_DATE,
       QNA_VISIBLE, QNA_FILE, QNA_VIEWS
FROM QNA
;
--QNA 하나 상세 보기
SELECT QNA_NO, QNA_TITLE, QNA_CONTENT,
       QNA_REG_DATE, QNA_VISIBLE, QNA_FILE, QNA_VIEWS
FROM QNA
WHERE QNA_NO = ?
;




