--회원가입(member, member_detail)
INSERT INTO MEMBER(MEMBER_NO, MEMBER_NAME, MEMBER_ID,
                   MEMBER_PASS, MEMBER_PHONE, MEMBER_EMAIL)
VALUES (MEMBER_SEQ.nextval, ?, ?, ?, ?, ?)
;
--책 추가
INSERT INTO BOOK(BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_INFO, BOOK_CATEGORY,
                 BOOK_IMAGE_URL, BOOK_INDEX, BOOK_PUBLISHER, BOOK_YOP,
                 BOOK_HOLDINGS, BOOK_LOAN, BOOK_RESERVATION)
VALUES (?, ?, ?, ?, ?, NULL, ?, ?, ?, 5, 0, 0)
;
--대출 추가
INSERT INTO LOAN(LOAN_NO, BOOK_NO, MEMBER_NO) VALUES (LOAN_SEQ.nextval, ?, ?)
;
--예약 추가
INSERT INTO RESERVATION VALUES(?, ?, SYSDATE)
;
--관심도서 추가
INSERT INTO FAVORITE(MEMBER_NO, BOOK_NO) VALUES (?, ?)
;
--희망도서 추가
INSERT INTO HOPE_BOOK(HOPE_NO, MEMBER_NO, BOOK_TITLE, BOOK_PUBLISHER, BOOK_AUTHOR)
VALUES (HOPE_BOOK_SEQ.nextval, ?, ?, ?, ?)
;
--질문하기
INSERT INTO QNA(QNA_NO, MEMBER_NO, QNA_TITLE, QNA_CONTENT, QNA_VISIBLE, QNA_FILE)
VALUES (QNA_SEQ.NEXTVAL, ?, ?, ?, ?, ?)
;
--답변하기
INSERT INTO REPLY(REPLY_NO, REPLY_CONTENT, QNA_NO, MEMBER_NO)
VALUES (REPLY_SEQ.NEXTVAL, ?, ?, ?)
;
--공지사항 내용 추가
INSERT INTO NOTICE(NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_FILE)
VALUES(NOTICE_SEQ.nextval, ?, ?, ?)
;
--FAQ 내용 추가
INSERT INTO FAQ(FAQ_NO, FAQ_QUESTION, FAQ_ANSWER, FAQ_CATEGORY)
VALUES(?, ?, ?, ?);