DROP TABLE HOPE_BOOK;
DROP TABLE LEAVE_MEMBER;
DROP TABLE LOAN;
DROP TABLE FAVORITE;
DROP TABLE RESERVATION;
DROP TABLE REPLY;
DROP TABLE FAQ;
DROP TABLE NOTICE;
DROP TABLE QNA;
DROP TABLE BOOK;
DROP TABLE MEMBER;

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE QNA_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE FAQ_SEQ;
DROP SEQUENCE HOPE_BOOK_SEQ;
DROP SEQUENCE REPLY_SEQ;
DROP SEQUENCE LEAVE_MEMBER_SEQ;
DROP SEQUENCE LOAN_SEQ;



