package com.itwill.librarian.sql;

public class NoticeSql {
	
	public final static String NOTICE_LIST = "SELECT NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REG_DATE, NOTICE_FILE, NOTICE_VIEWS FROM NOTICE";
	public final static String NOTICE_DETAIL = "SELECT NOTICE_TITLE, NOTICE_CONTENT, NOTICE_REG_DATE, NOTICE_FILE FROM NOTICE WHERE NOTICE_NO=?";
	public final static String NOTICE_INSERT = "INSERT INTO NOTICE VALUES(NOTICE_SEQ.nextval,?,?,SYSDATE,?,0)";
	public final static String NOTICE_UPDATE = "UPDATE NOTICE SET NOTICE_TITLE=?, NOTICE_CONTENT=?, NOTICE_FILE=? WHERE NOTICE_NO=?";
	public final static String NOTICE_DELETE = "DELETE FROM NOTICE WHERE NOTICE_NO=?";
	public final static String NOTICE_READ_COUNT = "UPDATE NOTICE SET NOTICE_VIEWS = NOTICE_VIEWS + 1 WHERE NOTICE_NO = ?";
	
}
